# This file was automatically generated by {{ $generated_by }}.

use strict;
use warnings;

{{ $use_perl }}

use ExtUtils::MakeMaker{{ $eumm_version }};

{{ $preamble }}

my {{ $WriteMakefile_args }}

my {{ $fallback_prereqs }}

{{ $mutate_config }}

unless ( eval { ExtUtils::MakeMaker->VERSION(6.63_03) } ) {
  delete $WriteMakefileArgs{TEST_REQUIRES};
  delete $WriteMakefileArgs{BUILD_REQUIRES};
  $WriteMakefileArgs{PREREQ_PM} = \%FallbackPrereqs;
}

delete $WriteMakefileArgs{CONFIGURE_REQUIRES}
  unless eval { ExtUtils::MakeMaker->VERSION(6.52) };

WriteMakefile(%WriteMakefileArgs);

{{ $postamble }}
